-- Starting Version 16
BEGIN;

-- IP Tracking
CREATE TABLE iptrk (
	ip		INET NOT NULL PRIMARY KEY,
	count		INTEGER NOT NULL DEFAULT 1,
	entered		TIMESTAMP NOT NULL DEFAULT NOW()::TIMESTAMP,
	last		TIMESTAMP NOT NULL DEFAULT NOW()::TIMESTAMP
);

-- Set the db version properly.
--Update Version.
UPDATE schema_metadata
   SET value = 17
 WHERE value = 16
   AND key = 'portal_schema_version';
COMMIT;
